apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
    name: hello-app
  namespace: operate-integrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
      name: hello-app
  template:
    metadata:
      labels:
        app: hello-app
        name: hello-app
    spec:
      containers:
      - name: hello-app
        image: central-quay-registry.apps.ocp4.example.com/finance/do480-hello-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
    name: hello-app
  name: hello-app
  namespace: operate-integrate
spec:
  ports:
  - port: 8080
  selector:
    name: hello-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-app
  labels:
    app: hello-app
    name: hello-app
  namespace: operate-integrate
spec:
  host: hello-app.apps.ocp4.example.com
  subdomain: ''
  to:
    kind: Service
    name: hello-app
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
