apiVersion: v1
items:
- apiVersion: apps.open-cluster-management.io/v1
  kind: Subscription
  metadata:
    annotations:
      apps.open-cluster-management.io/deployables: mysql/mysql-subscription-1-mysql-frontend-deployment,mysql/mysql-subscription-1-mysql-mysql-deployment,mysql/mysql-subscription-1-mysql-frontend-route,mysql/mysql-subscription-1-mysql-frontend-service,mysql/mysql-subscription-1-mysql-mysql-service
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/git-path: mysql
      apps.open-cluster-management.io/reconcile-option: merge
    creationTimestamp: "2023-05-23T10:11:22Z"
    generation: 4
    labels:
      app: mysql
      app.kubernetes.io/part-of: mysql
      apps.open-cluster-management.io/reconcile-rate: medium
    name: mysql-subscription-1
    namespace: mysql
    resourceVersion: "3080664"
    uid: 22098b4f-8dac-4554-b145-940a24613336
  spec:
    channel: ggithubcom-tosmi-do480-apps-ns/ggithubcom-tosmi-do480-apps
    placement:
      placementRef:
        kind: PlacementRule
        name: mysql-placement-1
    secondaryChannel: ""
    timewindow:
      daysofweek:
      - Tuesday
      hours:
      - end: 1:30PM
        start: 12:00AM
      location: Europe/Vienna
      windowtype: active
  status:
    lastUpdateTime: "2023-05-23T10:11:36Z"
    phase: Propagated
    statuses:
      local-cluster: {}
- apiVersion: apps.open-cluster-management.io/v1
  kind: Subscription
  metadata:
    annotations:
      apps.open-cluster-management.io/channel-generation: "1"
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/git-path: mysql
      apps.open-cluster-management.io/hosting-deployable: local-cluster/mysql-subscription-1-deployable-ppdls
      apps.open-cluster-management.io/hosting-subscription: mysql/mysql-subscription-1
      apps.open-cluster-management.io/reconcile-option: merge
      apps.open-cluster-management.io/sync-source: subnsdpl-/
      open-cluster-management.io/user-group: ""
      open-cluster-management.io/user-identity: ""
    creationTimestamp: "2023-05-23T10:11:29Z"
    generation: 2
    labels:
      app: mysql
      app.kubernetes.io/part-of: mysql
      apps.open-cluster-management.io/reconcile-rate: medium
      hosting-deployable-name: mysql-subscription-1-deployable
      subscription-pause: "false"
    name: mysql-subscription-1-local
    namespace: mysql
    resourceVersion: "3079727"
    uid: 18a70504-b7c5-4590-90f5-7b3cce33977d
  spec:
    channel: ggithubcom-tosmi-do480-apps-ns/ggithubcom-tosmi-do480-apps
    placement:
      local: true
    secondaryChannel: ""
    timewindow:
      daysofweek:
      - Tuesday
      hours:
      - end: 2:00AM
        start: 12:00AM
      location: Europe/Vienna
      windowtype: active
  status:
    ansiblejobs: {}
    lastUpdateTime: "2023-05-23T10:19:00Z"
    message: Blocked
    phase: Subscribed
    statuses:
      /:
        packages:
          ggithubcom-tosmi-do480-apps-Deployment-frontend:
            lastUpdateTime: "2023-05-23T10:11:30Z"
            phase: Subscribed
            resourceStatus: {}
          ggithubcom-tosmi-do480-apps-Deployment-mysql:
            lastUpdateTime: "2023-05-23T10:11:30Z"
            phase: Subscribed
            resourceStatus: {}
          ggithubcom-tosmi-do480-apps-Route-frontend:
            lastUpdateTime: "2023-05-23T10:11:29Z"
            phase: Subscribed
            resourceStatus: {}
          ggithubcom-tosmi-do480-apps-Service-frontend:
            lastUpdateTime: "2023-05-23T10:11:29Z"
            phase: Subscribed
            resourceStatus:
              loadBalancer: {}
          ggithubcom-tosmi-do480-apps-Service-mysql:
            lastUpdateTime: "2023-05-23T10:11:30Z"
            phase: Subscribed
            resourceStatus:
              loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
