apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: observability-bucket-4bbfb905-2802-469b-8885-eed723e1c548
      endpoint: rook-ceph-rgw-ocs-external-storagecluster-cephobjectstore.openshift-storage.svc:8080
      insecure: true
      access_key: JM3Q9CPG88KHZBJ765L7
      secret_key: ILkrCI7VDSBcU2vK4Agnn1bs5H498aLnMQeImqeS
